#
#  dnf install mongodb-org -y
#    cp mongo.repo /etc/yum.repos.d/mongo.repo
#
#    sed -i -e 's/127.0.0.1/0.0.0.0' /etc/mongod.conf
#    systemctl enable mongod
#    systemctl start mongod

- name: Copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb Server
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Search & replace mongodb listen address.
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes

