
    - name: Install nginx 1.24
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: copy nginx
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: "0644"