#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#dnf install nodejs -y
#
#APP_PREREQ
#npm install
#
#SYSTEMD

- name: Disable default Nodejs and enable nodejs 20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Load App Pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Load SystemD
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
