- name: Load NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

###Docker setup
#- name: Load Docker
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: docker